PKG-1722 update to 20230802.0
AnacondaRecipes/abseil-cpp-feedstock pull request #4
Opened 2023-08-16 08:53 UTC by M-Waszkiewicz-Anaconda

dependency for protobuf & grpc
- update to latest tag - 20230802.0
- add tests if libabsl_log_initialize exist - needed by protobuf >=4.0.0
[upstream](https://github.com/abseil/abseil-cpp/tree/20230802.0)

2023-08-16 08:54 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:22: patch_unnecessary: patch should not be in build when source/patches is not set
ERROR: clone/recipe/meta.yaml:325: missing_tests: No tests were found.
Errors were found

</details>

2023-08-16 09:08 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:22: patch_unnecessary: patch should not be in build when source/patches is not set
ERROR: clone/recipe/meta.yaml:325: missing_tests: No tests were found.
Errors were found

</details>

2023-08-16 09:11 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:22: patch_unnecessary: patch should not be in build when source/patches is not set
ERROR: clone/recipe/meta.yaml:325: missing_tests: No tests were found.
Errors were found

</details>

2023-08-16 09:47 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:22: patch_unnecessary: patch should not be in build when source/patches is not set
ERROR: clone/recipe/meta.yaml:325: missing_tests: No tests were found.
Errors were found

</details>

2023-08-16 09:58 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:22: patch_unnecessary: patch should not be in build when source/patches is not set
ERROR: clone/recipe/meta.yaml:325: missing_tests: No tests were found.
Errors were found

</details>

2023-08-16 10:16 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:22: patch_unnecessary: patch should not be in build when source/patches is not set
ERROR: clone/recipe/meta.yaml:325: missing_tests: No tests were found.
Errors were found

</details>

2023-08-16 13:28 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:22: patch_unnecessary: patch should not be in build when source/patches is not set
ERROR: clone/recipe/meta.yaml:325: missing_tests: No tests were found.
Errors were found

</details>

2023-08-16 13:33 UTC, M-Waszkiewicz-Anaconda commented on recipe/conda_build_config.yaml
> +macos_min_version:         # [osx and x86]
@boldorider4 if you wonder about the solution for the problem we talked about, here it is

2023-08-16 16:51 UTC, JeanChristopheMorinPerso requested changes

2023-08-16 16:51 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    # - osx_framework_fix.diff  # [osx]
You could remove the patches from the repo if we don't use them anymore.

2023-08-16 16:52 UTC, ViridianMelody approved these changes
Looks good to me aside from one comment.

2023-08-16 16:52 UTC, ViridianMelody commented on recipe/meta.yaml
> +    # - remove-4221.patch  # [win]
If the only remaining patch is for osx, we should remove `m2-patch` and set `patch` to osx only.

2023-08-17 09:44 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:321: missing_tests: No tests were found.
Errors were found

</details>

2023-08-17 10:28 UTC, akabanovs approved these changes
LGTM

2023-08-17 10:32 UTC, merged

2023-08-17 10:33 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:321: missing_tests: No tests were found.
Errors were found

</details>